DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

CREATE TABLE burgers(
	id INTEGER(11) AUTO_INCREMENT NOT NULL,
    burger VARCHAR(80) NOT NULL,
    devoured BOOLEAN DEFAULT 0,
    
    PRIMARY KEY(id)
);